# Generated by Django 4.1.7 on 2023-04-25 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('customerContactPerson', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('link', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('Salesfunnel', models.CharField(max_length=100)),
                ('customerServiceRepresentative', models.CharField(max_length=100)),
                ('Costumer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.costumer')),
            ],
            options={
                'verbose_name': 'Opportunities',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('Opportunity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('Software Engineer Senior', 'SoftwareEngineerSenior'), ('Software Engineer Regular', 'SoftwareEngineerRegular'), ('RequirementsEngineer', 'RequirementsEngineer'), ('Software Reliability Engineer', 'SoftwareReliabilityEngineer'), ('Quality Engineer', 'QualityEngineer'), ('UI_UX Designer', 'UI/UXDesigner'), ('Technical Architect', 'TechnicalArchitect'), ('Project Manager', 'ProjectManager'), ('Technical Consultant', 'TechnicalConsultant'), ('Agile Coach', 'Agile Coach'), ('Data Scientist', 'DataScientist')], default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('country', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('zipCode', models.CharField(max_length=100, null=True)),
                ('costumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend_api.costumer')),
            ],
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(null=True)),
                ('Phase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.phase')),
                ('Role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.role')),
            ],
        ),
    ]
