# Generated by Django 4.1.7 on 2023-04-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='customerServiceRepresentative',
            new_name='customerRepresentative',
        ),
    ]
