# Generated by Django 4.1.7 on 2023-04-25 12:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_rename_customerservicerepresentative_opportunity_customerrepresentative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
