# Generated by Django 4.1.7 on 2023-05-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_rename_salesfunnel_opportunity_salesfunnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='phases_json',
            field=models.JSONField(default='[]'),
        ),
    ]
