# Generated by Django 4.1.7 on 2023-05-10 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_opportunity_phases_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleassignment',
            name='Phase_id',
        ),
        migrations.RemoveField(
            model_name='roleassignment',
            name='Role_id',
        ),
        migrations.DeleteModel(
            name='Phase',
        ),
        migrations.DeleteModel(
            name='RoleAssignment',
        ),
    ]
