# Generated by Django 4.1.7 on 2023-06-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0009_alter_role_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='Customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='backend_api.customer'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('Software Engineer Senior', 'SoftwareEngineerSenior'), ('Software Engineer Regular', 'SoftwareEngineerRegular'), ('Requirements Engineer', 'RequirementsEngineer'), ('Software Reliability Engineer', 'SoftwareReliabilityEngineer'), ('Quality Engineer', 'QualityEngineer'), ('UI_UX Designer', 'UI/UXDesigner'), ('Technical Architect', 'TechnicalArchitect'), ('Project Manager', 'ProjectManager'), ('Technical Consultant', 'TechnicalConsultant'), ('Agile Coach', 'Agile Coach'), ('Data Scientist', 'DataScientist')], default=0, max_length=100),
        ),
    ]
